# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VideoPlayer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VideoPlayer(object):
    def setupUi(self, VideoPlayer):
        VideoPlayer.setObjectName("VideoPlayer")
        VideoPlayer.resize(777, 572)
        VideoPlayer.setStyleSheet("QMainWindow {\n"
"        background: rgb(222,164,189);\n"
"        background: linear-gradient(90deg, rgba(222,164,189,1) 0%, rgba(148,187,233,1) 85%);\n"
"        border: 1px solid #2980B9;\n"
"    }\n"
"    \n"
"    QMainWindow::separator {\n"
"        background: rgb(222,164,189);\n"
"        background: linear-gradient(90deg, rgba(222,164,189,1) 0%, rgba(148,187,233,1) 85%);\n"
"        width: 2px;\n"
"        height: 2px;\n"
"    }\n"
"    \n"
"    QMainWindow::separator:hover {\n"
"       background: rgb(222,164,189);\n"
"        background: linear-gradient(90deg, rgba(222,164,189,1) 0%, rgba(148,187,233,1) 85%);\n"
"    }\n"
"    ")
        VideoPlayer.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(VideoPlayer)
        self.centralwidget.setObjectName("centralwidget")
        self.btnBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowse.setGeometry(QtCore.QRect(180, 90, 81, 31))
        self.btnBrowse.setStyleSheet("QPushButton {\n"
"        background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"            stop:0 rgba(255, 168, 0, 255), stop:1 rgba(255, 87, 34, 255));\n"
"        border: 2px solid #d35400;\n"
"        color: white;\n"
"        padding: 8px 16px;\n"
"        border-radius: 10px;\n"
"    }\n"
"    \n"
"    QPushButton:hover {\n"
"        background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"            stop:0 rgba(255, 138, 0, 255), stop:1 rgba(255, 71, 26, 255));\n"
"        border: 2px solid #d35400;\n"
"        color: white;\n"
"        padding: 8px 16px;\n"
"        border-radius: 10px;\n"
"        box-shadow: 0px 3px 10px rgba(0, 0, 0, 0.3);\n"
"    }\n"
"    \n"
"    QPushButton:pressed {\n"
"        background-color: rgba(255, 87, 34, 255);\n"
"        border: 2px solid #d35400;\n"
"        color: white;\n"
"        padding: 8px 16px;\n"
"        border-radius: 10px;\n"
"    }")
        self.btnBrowse.setFlat(False)
        self.btnBrowse.setObjectName("btnBrowse")
        self.Speedslider = QtWidgets.QSlider(self.centralwidget)
        self.Speedslider.setGeometry(QtCore.QRect(150, 450, 160, 22))
        self.Speedslider.setMinimumSize(QtCore.QSize(160, 0))
        self.Speedslider.setMaximumSize(QtCore.QSize(160, 22))
        self.Speedslider.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        background-color: rgba(52, 73, 94, 200);  /* Semi-transparent background color */\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        border: 1px solid rgba(0, 0, 0, 50);  /* Semi-transparent border */\n"
"        box-shadow: 2px 2px 5px rgba(0, 0, 0, 50);  /* Shadow effect */\n"
"    }")
        self.Speedslider.setMinimum(1)
        self.Speedslider.setMaximum(8)
        self.Speedslider.setValue(4)
        self.Speedslider.setPageStep(1)
        self.Speedslider.setOrientation(QtCore.Qt.Horizontal)
        self.Speedslider.setObjectName("Speedslider")
        self.MainHeadinglbl = QtWidgets.QLabel(self.centralwidget)
        self.MainHeadinglbl.setGeometry(QtCore.QRect(300, 20, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.MainHeadinglbl.setFont(font)
        self.MainHeadinglbl.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        background-color: rgba(52, 73, 94, 200);  /* Semi-transparent background color */\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        border: 1px solid rgba(0, 0, 0, 50);  /* Semi-transparent border */\n"
"        box-shadow: 2px 2px 5px rgba(0, 0, 0, 50);  /* Shadow effect */\n"
"    }")
        self.MainHeadinglbl.setObjectName("MainHeadinglbl")
        self.Speedlbl = QtWidgets.QLabel(self.centralwidget)
        self.Speedlbl.setGeometry(QtCore.QRect(70, 450, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Speedlbl.setFont(font)
        self.Speedlbl.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        background-color: rgba(52, 73, 94, 200);  /* Semi-transparent background color */\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        border: 1px solid rgba(0, 0, 0, 50);  /* Semi-transparent border */\n"
"        box-shadow: 2px 2px 5px rgba(0, 0, 0, 50);  /* Shadow effect */\n"
"    }")
        self.Speedlbl.setObjectName("Speedlbl")
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setGeometry(QtCore.QRect(640, 190, 22, 211))
        self.verticalSlider.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        background-color: rgba(52, 73, 94, 200);  /* Semi-transparent background color */\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        border: 1px solid rgba(0, 0, 0, 50);  /* Semi-transparent border */\n"
"        box-shadow: 2px 2px 5px rgba(0, 0, 0, 50);  /* Shadow effect */\n"
"    }")
        self.verticalSlider.setMaximum(255)
        self.verticalSlider.setValue(127)
        self.verticalSlider.setMinimum(0)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.Speedlbl_2 = QtWidgets.QLabel(self.centralwidget)
        self.Speedlbl_2.setGeometry(QtCore.QRect(670, 270, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Speedlbl_2.setFont(font)
        self.Speedlbl_2.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        background-color: rgba(52, 73, 94, 200);  /* Semi-transparent background color */\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        border: 1px solid rgba(0, 0, 0, 50);  /* Semi-transparent border */\n"
"        box-shadow: 2px 2px 5px rgba(0, 0, 0, 50);  /* Shadow effect */\n"
"    }")
        self.Speedlbl_2.setObjectName("Speedlbl_2")
        self.lblDataSource = QtWidgets.QLabel(self.centralwidget)
        self.lblDataSource.setGeometry(QtCore.QRect(40, 90, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblDataSource.setFont(font)
        self.lblDataSource.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        background-color: rgba(52, 73, 94, 200);  /* Semi-transparent background color */\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        border: 1px solid rgba(0, 0, 0, 50);  /* Semi-transparent border */\n"
"        box-shadow: 2px 2px 5px rgba(0, 0, 0, 50);  /* Shadow effect */\n"
"    }")
        self.lblDataSource.setObjectName("lblDataSource")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 180, 541, 241))
        self.label.setMinimumSize(QtCore.QSize(0, 221))
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setPixmap(QtGui.QPixmap("C:/Users/HS/Downloads/Green and White Doodle Group Project Presentation.jpg"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.btnRefresh = QtWidgets.QPushButton(self.centralwidget)
        self.btnRefresh.setGeometry(QtCore.QRect(520, 140, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnRefresh.setFont(font)
        self.btnRefresh.setStyleSheet("QPushButton {\n"
"        background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"            stop:0 rgba(39, 174, 96, 255), stop:1 rgba(46, 204, 113, 255));\n"
"        border: 1px solid #27ae60;\n"
"        color: white;\n"
"        padding: 8px 16px;\n"
"        border-radius: 5px;\n"
"    }\n"
"    \n"
"    QPushButton:hover {\n"
"        background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"            stop:0 rgba(22, 160, 133, 255), stop:1 rgba(39, 174, 96, 255));\n"
"        border: 1px solid #2ecc71;\n"
"        color: white;\n"
"        padding: 8px 16px;\n"
"        border-radius: 5px;\n"
"        box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.3);\n"
"    }\n"
"    \n"
"    QPushButton:pressed {\n"
"        background-color: rgba(39, 174, 96, 255);\n"
"        border: 1px solid #27ae60;\n"
"        color: white;\n"
"        padding: 8px 16px;\n"
"        border-radius: 5px;\n"
"    }")
        self.btnRefresh.setAutoDefault(True)
        self.btnRefresh.setObjectName("btnRefresh")
        self.rdbtnSort = QtWidgets.QRadioButton(self.centralwidget)
        self.rdbtnSort.setGeometry(QtCore.QRect(270, 140, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rdbtnSort.setFont(font)
        self.rdbtnSort.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        background-color: rgba(52, 73, 94, 200);  /* Semi-transparent background color */\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        border: 1px solid rgba(0, 0, 0, 50);  /* Semi-transparent border */\n"
"        box-shadow: 2px 2px 5px rgba(0, 0, 0, 50);  /* Shadow effect */\n"
"    }")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("webcam.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rdbtnSort.setIcon(icon)
        self.rdbtnSort.setObjectName("rdbtnSort")
        self.btnBrowse_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowse_2.setGeometry(QtCore.QRect(270, 90, 111, 31))
        self.btnBrowse_2.setStyleSheet("QPushButton {\n"
"        background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"            stop:0 rgba(231, 76, 60, 255), stop:1 rgba(192, 57, 43, 255));\n"
"        border: 1px solid #c0392b;\n"
"        color: white;\n"
"        padding: 10px 20px;\n"
"        border-radius: 5px;\n"
"        icon-size: 32px;  /* Adjust the icon size as needed */\n"
"        icon-color: white;  /* Set the icon color */\n"
"        icon-alignment: center;  /* Center the icon */\n"
"    }\n"
"    \n"
"    QPushButton:hover {\n"
"        background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"            stop:0 rgba(192, 57, 43, 255), stop:1 rgba(231, 76, 60, 255));\n"
"        border: 1px solid #e74c3c;\n"
"        color: white;\n"
"        padding: 10px 20px;\n"
"        border-radius: 5px;\n"
"        box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.3);\n"
"    }\n"
"    \n"
"    QPushButton:pressed {\n"
"        background-color: rgba(192, 57, 43, 255);\n"
"        border: 1px solid #c0392b;\n"
"        color: white;\n"
"        padding: 10px 20px;\n"
"        border-radius: 5px;\n"
"    }")
        self.btnBrowse_2.setFlat(False)
        self.btnBrowse_2.setObjectName("btnBrowse_2")
        self.availableCameras = QtWidgets.QComboBox(self.centralwidget)
        self.availableCameras.setGeometry(QtCore.QRect(630, 100, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.availableCameras.setFont(font)
        self.availableCameras.setObjectName("availableCameras")
        self.lblDataSource_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblDataSource_2.setGeometry(QtCore.QRect(490, 100, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblDataSource_2.setFont(font)
        self.lblDataSource_2.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        background-color: rgba(52, 73, 94, 200);  /* Semi-transparent background color */\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        border: 1px solid rgba(0, 0, 0, 50);  /* Semi-transparent border */\n"
"        box-shadow: 2px 2px 5px rgba(0, 0, 0, 50);  /* Shadow effect */\n"
"    }")
        self.lblDataSource_2.setObjectName("lblDataSource_2")
        VideoPlayer.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(VideoPlayer)
        self.statusbar.setObjectName("statusbar")
        VideoPlayer.setStatusBar(self.statusbar)

        self.retranslateUi(VideoPlayer)
        QtCore.QMetaObject.connectSlotsByName(VideoPlayer)

    def retranslateUi(self, VideoPlayer):
        _translate = QtCore.QCoreApplication.translate
        VideoPlayer.setWindowTitle(_translate("VideoPlayer", "MainWindow"))
        self.btnBrowse.setText(_translate("VideoPlayer", "Browse"))
        self.MainHeadinglbl.setText(_translate("VideoPlayer", "Video Player"))
        self.Speedlbl.setText(_translate("VideoPlayer", "Speed"))
        self.Speedlbl_2.setText(_translate("VideoPlayer", "Grey Scale"))
        self.lblDataSource.setText(_translate("VideoPlayer", "Import Video"))
        self.btnRefresh.setText(_translate("VideoPlayer", "Clear Video"))
        self.rdbtnSort.setText(_translate("VideoPlayer", "Webcam"))
        self.btnBrowse_2.setText(_translate("VideoPlayer", "Capture Video"))
        self.lblDataSource_2.setText(_translate("VideoPlayer", "Select Camera"))

