# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImagePlayer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImagePlayer(object):
    def setupUi(self, ImagePlayer):
        ImagePlayer.setObjectName("ImagePlayer")
        ImagePlayer.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ImagePlayer)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 160, 541, 241))
        self.label.setMinimumSize(QtCore.QSize(0, 221))
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setPixmap(QtGui.QPixmap("C:/Users/HS/Downloads/Green and White Doodle Group Project Presentation.jpg"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.MainHeadinglbl = QtWidgets.QLabel(self.centralwidget)
        self.MainHeadinglbl.setGeometry(QtCore.QRect(270, 0, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.MainHeadinglbl.setFont(font)
        self.MainHeadinglbl.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        background-color: rgba(52, 73, 94, 200);  /* Semi-transparent background color */\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        border: 1px solid rgba(0, 0, 0, 50);  /* Semi-transparent border */\n"
"        box-shadow: 2px 2px 5px rgba(0, 0, 0, 50);  /* Shadow effect */\n"
"    }")
        self.MainHeadinglbl.setObjectName("MainHeadinglbl")
        self.btnBrowse_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowse_2.setGeometry(QtCore.QRect(250, 70, 111, 31))
        self.btnBrowse_2.setStyleSheet("QPushButton {\n"
"        background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"            stop:0 rgba(231, 76, 60, 255), stop:1 rgba(192, 57, 43, 255));\n"
"        border: 1px solid #c0392b;\n"
"        color: white;\n"
"        padding: 10px 20px;\n"
"        border-radius: 5px;\n"
"        icon-size: 32px;  /* Adjust the icon size as needed */\n"
"        icon-color: white;  /* Set the icon color */\n"
"        icon-alignment: center;  /* Center the icon */\n"
"    }\n"
"    \n"
"    QPushButton:hover {\n"
"        background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"            stop:0 rgba(192, 57, 43, 255), stop:1 rgba(231, 76, 60, 255));\n"
"        border: 1px solid #e74c3c;\n"
"        color: white;\n"
"        padding: 10px 20px;\n"
"        border-radius: 5px;\n"
"        box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.3);\n"
"    }\n"
"    \n"
"    QPushButton:pressed {\n"
"        background-color: rgba(192, 57, 43, 255);\n"
"        border: 1px solid #c0392b;\n"
"        color: white;\n"
"        padding: 10px 20px;\n"
"        border-radius: 5px;\n"
"    }")
        self.btnBrowse_2.setFlat(False)
        self.btnBrowse_2.setObjectName("btnBrowse_2")
        self.availableCameras = QtWidgets.QComboBox(self.centralwidget)
        self.availableCameras.setGeometry(QtCore.QRect(600, 80, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.availableCameras.setFont(font)
        self.availableCameras.setObjectName("availableCameras")
        self.availableFilters = QtWidgets.QComboBox(self.centralwidget)
        self.availableFilters.setGeometry(QtCore.QRect(140, 420, 131, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.availableFilters.setFont(font)
        self.availableFilters.setObjectName("availableFilters")
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setGeometry(QtCore.QRect(610, 250, 22, 211))
        self.verticalSlider.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        background-color: rgba(52, 73, 94, 200);  /* Semi-transparent background color */\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        border: 1px solid rgba(0, 0, 0, 50);  /* Semi-transparent border */\n"
"        box-shadow: 2px 2px 5px rgba(0, 0, 0, 50);  /* Shadow effect */\n"
"    }")
        self.verticalSlider.setMaximum(255)
        self.verticalSlider.setValue(127)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.Speedlbl_2 = QtWidgets.QLabel(self.centralwidget)
        self.Speedlbl_2.setGeometry(QtCore.QRect(640, 250, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Speedlbl_2.setFont(font)
        self.Speedlbl_2.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        background-color: rgba(52, 73, 94, 200);  /* Semi-transparent background color */\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        border: 1px solid rgba(0, 0, 0, 50);  /* Semi-transparent border */\n"
"        box-shadow: 2px 2px 5px rgba(0, 0, 0, 50);  /* Shadow effect */\n"
"    }")
        self.Speedlbl_2.setObjectName("Speedlbl_2")
        self.lblDataSource_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblDataSource_2.setGeometry(QtCore.QRect(460, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblDataSource_2.setFont(font)
        self.lblDataSource_2.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        background-color: rgba(52, 73, 94, 200);  /* Semi-transparent background color */\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        border: 1px solid rgba(0, 0, 0, 50);  /* Semi-transparent border */\n"
"        box-shadow: 2px 2px 5px rgba(0, 0, 0, 50);  /* Shadow effect */\n"
"    }")
        self.lblDataSource_2.setObjectName("lblDataSource_2")
        self.btnRefresh = QtWidgets.QPushButton(self.centralwidget)
        self.btnRefresh.setGeometry(QtCore.QRect(480, 120, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnRefresh.setFont(font)
        self.btnRefresh.setStyleSheet("QPushButton {\n"
"        background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"            stop:0 rgba(39, 174, 96, 255), stop:1 rgba(46, 204, 113, 255));\n"
"        border: 1px solid #27ae60;\n"
"        color: white;\n"
"        padding: 8px 16px;\n"
"        border-radius: 5px;\n"
"    }\n"
"    \n"
"    QPushButton:hover {\n"
"        background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"            stop:0 rgba(22, 160, 133, 255), stop:1 rgba(39, 174, 96, 255));\n"
"        border: 1px solid #2ecc71;\n"
"        color: white;\n"
"        padding: 8px 16px;\n"
"        border-radius: 5px;\n"
"        box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.3);\n"
"    }\n"
"    \n"
"    QPushButton:pressed {\n"
"        background-color: rgba(39, 174, 96, 255);\n"
"        border: 1px solid #27ae60;\n"
"        color: white;\n"
"        padding: 8px 16px;\n"
"        border-radius: 5px;\n"
"    }")
        self.btnRefresh.setAutoDefault(True)
        self.btnRefresh.setObjectName("btnRefresh")
        self.lblDataSource = QtWidgets.QLabel(self.centralwidget)
        self.lblDataSource.setGeometry(QtCore.QRect(10, 70, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblDataSource.setFont(font)
        self.lblDataSource.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        background-color: rgba(52, 73, 94, 200);  /* Semi-transparent background color */\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        border: 1px solid rgba(0, 0, 0, 50);  /* Semi-transparent border */\n"
"        box-shadow: 2px 2px 5px rgba(0, 0, 0, 50);  /* Shadow effect */\n"
"    }")
        self.lblDataSource.setObjectName("lblDataSource")
        self.lblDataSource_3 = QtWidgets.QLabel(self.centralwidget)
        self.lblDataSource_3.setGeometry(QtCore.QRect(50, 420, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblDataSource_3.setFont(font)
        self.lblDataSource_3.setStyleSheet("QLabel {\n"
"        color: white;\n"
"        background-color: rgba(52, 73, 94, 200);  /* Semi-transparent background color */\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        border: 1px solid rgba(0, 0, 0, 50);  /* Semi-transparent border */\n"
"        box-shadow: 2px 2px 5px rgba(0, 0, 0, 50);  /* Shadow effect */\n"
"    }")
        self.lblDataSource_3.setObjectName("lblDataSource_3")
        self.btnBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowse.setGeometry(QtCore.QRect(150, 70, 91, 31))
        self.btnBrowse.setStyleSheet("QPushButton {\n"
"        background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"            stop:0 rgba(255, 168, 0, 255), stop:1 rgba(255, 87, 34, 255));\n"
"        border: 2px solid #d35400;\n"
"        color: white;\n"
"        padding: 8px 16px;\n"
"        border-radius: 10px;\n"
"    }\n"
"    \n"
"    QPushButton:hover {\n"
"        background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"            stop:0 rgba(255, 138, 0, 255), stop:1 rgba(255, 71, 26, 255));\n"
"        border: 2px solid #d35400;\n"
"        color: white;\n"
"        padding: 8px 16px;\n"
"        border-radius: 10px;\n"
"        box-shadow: 0px 3px 10px rgba(0, 0, 0, 0.3);\n"
"    }\n"
"    \n"
"    QPushButton:pressed {\n"
"        background-color: rgba(255, 87, 34, 255);\n"
"        border: 2px solid #d35400;\n"
"        color: white;\n"
"        padding: 8px 16px;\n"
"        border-radius: 10px;\n"
"    }")
        self.btnBrowse.setFlat(False)
        self.btnBrowse.setObjectName("btnBrowse")
        ImagePlayer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ImagePlayer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuVideo = QtWidgets.QMenu(self.menubar)
        self.menuVideo.setObjectName("menuVideo")
        self.menuImage_Player = QtWidgets.QMenu(self.menubar)
        self.menuImage_Player.setObjectName("menuImage_Player")
        ImagePlayer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ImagePlayer)
        self.statusbar.setObjectName("statusbar")
        ImagePlayer.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuVideo.menuAction())
        self.menubar.addAction(self.menuImage_Player.menuAction())

        self.retranslateUi(ImagePlayer)
        QtCore.QMetaObject.connectSlotsByName(ImagePlayer)

    def retranslateUi(self, ImagePlayer):
        _translate = QtCore.QCoreApplication.translate
        ImagePlayer.setWindowTitle(_translate("ImagePlayer", "ImagePlayer"))
        self.MainHeadinglbl.setText(_translate("ImagePlayer", "Image Player"))
        self.btnBrowse_2.setText(_translate("ImagePlayer", "Capture"))
        self.Speedlbl_2.setText(_translate("ImagePlayer", "Grey Scale"))
        self.lblDataSource_2.setText(_translate("ImagePlayer", "Select Camera"))
        self.btnRefresh.setText(_translate("ImagePlayer", "Clear"))
        self.lblDataSource.setText(_translate("ImagePlayer", "Import Image"))
        self.lblDataSource_3.setText(_translate("ImagePlayer", "  Filters"))
        self.btnBrowse.setText(_translate("ImagePlayer", "Browse"))
        self.menuVideo.setTitle(_translate("ImagePlayer", "Video Player"))
        self.menuImage_Player.setTitle(_translate("ImagePlayer", "Image Player"))
